# Generated by Django 2.2.13 on 2020-07-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=200)),
                ('companyName', models.CharField(max_length=200)),
                ('startDate', models.CharField(max_length=200)),
                ('endDate', models.CharField(max_length=200)),
                ('jobDescription', models.TextField()),
                ('responsibilities', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='details',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
